# Generated by Django 4.2.8 on 2023-12-04 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='position',
            new_name='lastname',
        ),
        migrations.AddField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='middle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
